- MixItUp.WPF/Controls/Actions/ActionContainerControl.xaml.cs
This fixes issue #40 by preventing the loaded event from creating a new actionControl when it is moved.
> Add null check around actionControl to prevent the loaded event from erasing existing values.

- MixItUp.Base/Services/IFileService.cs
- MixItUp.Base/Statistics/StatisticsTracker.cs
- MixItUp.Desktop/Services/WindowsFileService.cs
- MixItUp.WPF/Controls/Actions/CounterActionControl.xaml.cs
Bonus fix: Fix background null ref when loading the first time
This should address #132
> Fix crash opening the counters folder

- MixItUp.Base/ViewModel/Import/ScorpBotData.cs
It was possible for very large numbers (999999999999999) to be in the scorpbot data.  This would fail to parse.  Let's use a BigInteger to ensure we can support STUPID large values, then bounds check, and clamp to int.MinValue and int.MaxValue.
> Add bounds checking around scorpbot data import.

- MixItUp.WPF/Controls/MainControls/EventsControl.xaml
- MixItUp.WPF/Controls/MainControls/EventsControl.xaml.cs
The events needed to be routed because the DataContext isn't the CommandBase.  So we need to handle the Play/Stop events and trigger the event.
> Fix Play and Stop Buttons for new events

- MixItUp.Desktop/Services/DesktopSongRequestService.cs
Not all song links have the ? in the URI.  Changed the logic to work in both cases.
Also, small refactor to use constants.
> Must set songId when link doesn't have params

- MixItUp.Base/Actions/GameQueueAction.cs
- MixItUp.Base/Commands/PermissionsCommandBase.cs
- MixItUp.Base/Commands/PreMadeChatCommands.cs
- MixItUp.Base/ViewModel/Requirement/RequirementViewModel.cs
- MixItUp.WPF/Controls/MainControls/GiveawayControl.xaml.cs
This ensures we allow new followers and subscribers to use locked commands quickly.  This really helps with the queue join and giveaway commands.
> When a user fails a roles check, force a refresh

- MixItUp.Base/ViewModel/User/UserViewModel.cs
Removed chatRoles: No reason to hold the values
Wrap access to this.mixerRoles in lock to ensure thread safety
Calculate RolesDisplayString and this.mixerRoles one time
Clean up this.MixerRole accesses to be more efficient (Overlaps/Switch, etc)
> Clean up the locking and logic around MixerRoles

- MixItUp.WPF/Controls/Requirement/CooldownRequirementControl.xaml.cs
Without this, then there are duplicates in the list.
> Cooldown groups need to be distinct

- MixItUp.Base/ViewModel/Chat/ChatMessageViewModel.cs
- MixItUp.WPF/Windows/Command/CommandWindow.xaml.cs
CRASHING EXCEPTION: System.InvalidCastException: Unable to cast object of type ‘MixItUp.WPF.Controls.Command.InteractiveTextBoxCommandDetailsControl’ to type ‘MixItUp.WPF.Controls.Command.InteractiveButtonCommandDetailsControl’.
at MixItUp.WPF.Windows.Command.CommandWindow.<OnLoaded>d__8.MoveNext() in S:\Code\mixer-mixitup\MixItUp.WPF\Windows\Command\CommandWindow.xaml.cs:line 67
> Fix invalid cast exception

- MixItUp.Base/MixerAPI/ChatClientWrapper.cs
Basically, Task.Delay need to take the cancellation token so it can abort if immediately if Cancel is called. These throw, and the background task exits immediately and cleanly.  Then the reconnect will restart the background tasks.
> Fix Timers and other background task when reconnecting

- MixItUp.Base/ChannelSession.cs
- MixItUp.Base/IChannelSettings.cs
- MixItUp.Base/Services/ITelemetryService.cs
- MixItUp.Desktop/DesktopChannelSettings.cs
- MixItUp.Desktop/Services/DesktopTelemetryService.cs
We generate a new GUID when settings doesn't have one, this will allow us to track users without storing any directly uniquely identifying information.
> Add UserId to telemetry

- MixItUp.WPF/Controls/MainControls/MainMenuControl.xaml.cs
Telemetry caught the issue here where sometimes it would fail.  This list isn't thread safe, so we need to lock around usage.
> Add locking around list usage

- MixItUp.Base/Statistics/StatisticDataTracker.cs
- MixItUp.Base/Util/Logger.cs
This is already logged in the HandleCrash code. This is causing exceptions to be double logged.
Also fix crash when using Linq on changing lists.
> Remove double log and fix crash

- MixItUp.Desktop/Services/OBSService.cs
- obs-websocket-dotnet/OBSWebsocket.cs
The reconnection logic was block after a failed connection, and the GetAuthInfo would never return.  Then the reconnection would trigger again, and again.
Instead, I changed the logic to block on Connect (which has a timeout already).  I tested this by closing/reopening OBS Studio a lot leaving it running and off for various times. Each time, it reconnected perfectly and all threads were maintained and stable.
> Change reconnect logic to ensure it doesn't block during reconnect path

- MixItUp.Desktop/Services/DesktopSongRequestService.cs
- MixItUp.Desktop/Services/SpotifyService.cs
If the playlist fails to play, it can cause a null ref exception to be throw, added a check
The offset should be based on the number of songs returned.  It seems the API returns 100 now.
> Fix spotify playlist issues

- MixItUp.Base/MixerAPI/ChatClientWrapper.cs
- MixItUp.WPF/Controls/Chat/ChatMessageControl.xaml.cs
- MixItUp.WPF/Controls/MainControls/ChatControl.xaml
- MixItUp.WPF/Controls/MainControls/ChatControl.xaml.cs
Add WhisperWithResponse to allow us to get the response chat message
Change tagging logic to be easier to read/process (tags whipsers to streamer, and the streamer's tag)
Add right click message to whisper the user.
Handle Whisper response and add the message. (Fixes Issue #260)
**NOTE: This does NOT add right click to the user in the user list.  Currently, that brings up the user details window.  So, we'd have to either, add a button to that page, or create a right click context menu and change the behavior significantly.  Thoughts?**
> Fix things related to whispers

- MixItUp.Base/MixerAPI/ConstellationClientWrapper.cs
- MixItUp.Base/MixerAPI/InteractiveClientWrapper.cs
- MixItUp.WPF/Controls/MainControls/InteractiveControl.xaml.cs
Check this out and let me know what you think. I'm just caching the interactive data (unless the user presses the refresh button to force the refresh).  During launch, we run this code like 5 times, which refreshes ALL games too.... 5 times. it added a LOT to the launch time. Also, disabled the known broken Skill Catalog lookup since it added a 1 second delay as well due to the error.
> This is an attempt to speed up login

- MixItUp.WPF/Controls/MainControls/ChannelControl.xaml.cs
The signs do not match the corresponding inequality values. e.g. `viewers < 25` means `when viewer count is less than 25`. `viewers > 25` means `when viewer count is greater than 25`. This is only an error for the Name strings; the queries in `FindChannelToRaidButton_Click` are correct. Brought to you by [Gouda](https://mixer.com/Gouda). 😄
> Fix inequality signs in RaidSearchCriteriaEnum

- MixItUp.Base/Util/SpecialIdentifierStringBuilder.cs
First, the random replacement wasn't honoring the identifierHeader prefix.
Next, a random item should never be considered possible if the user has "0" of them, right?  The idea is that the streamer would want to pick a random one from that user's inventory (1 or more).
> Fix target user random inventory bugs

- MixItUp.Base/Util/GlobalEvents.cs
Looks like a copy/paste error, checks OnDonationOccurred but calls OnBitsOccured.
It may also make sense to refactor these to use the C# 6 null conditional:
```csharp
public static void BitsOccurred(TwitchUserBitsCheeredModel bitsCheer)
{
GlobalEvents?.OnBitsOccurred(null, bitsCheer);
}
```
> Fix wrong null check for BitsOccurred

- MixItUp.Base/Actions/SpecialIdentifierAction.cs
I ran across an issue, when passing URL params to an overlay action, where some characters (a question mark in this case) would cause the remainder of the param to be ignored.
This change would allow the identifier to be UrlEncoded before being used in an overlay web page string.
I imagine it being used as below:
`![image](https://user-images.githubusercontent.com/3059536/91643209-cbe17b00-e9f6-11ea-8e2b-cae7ae9dfbce.png)
Update:
I just realized that web request may already URL encode, but I did run into this issue when passing a parameter to a web page via an overlay action.
> Add UrlEncode as a ProcessStringFunction
