SaviorXTanren/mixer-mixitup

MixItUp.Base/Actions/OverlayAction.cs
This is an idea, and not one you have to accept. But I tested it out and it actually feels nice, and breaks up the repetition that some animations have.  If you don't like it, let me know and I'll abandon the PR.
=> Add a Random option to overlay animation values

MixItUp.Base/ViewModel/User/UserViewModel.cs
It was removed in this commit:
https://github.com/SaviorXTanren/mixer-mixitup/commit/496dcdc59997a0955e4a03b618b74b743fdd1536#diff-5765ec644915dff31ff0b16bc63ec5ab
=> Need the UserWithChannelModel to get the GameTypeId.

MixItUp.Base/Commands/PreMadeChatCommands.cs
Create GameInformation
Change !steamgame to use this GameInformation
Change !game to try Xbox first
Add !xboxgame command to query Xbox game data
=> Add !xboxgame command

MixItUp.Base/Commands/CommandBase.cs, MixItUp.WPF/Controls/Command/ActionGroupCommandDetailsControl.xaml, MixItUp.WPF/Controls/Command/ActionGroupCommandDetailsControl.xaml.cs
Also exposed it to ActionGroup, so they can play one randomly
=> Add IsRandomized to CommandBase

MixItUp.Base/IChannelSettings.cs, MixItUp.Base/MixerAPI/ChatClientWrapper.cs, MixItUp.Base/ViewModel/User/UserViewModel.cs, MixItUp.Desktop/DesktopChannelSettings.cs, MixItUp.WPF/Controls/Chat/ChatMessageHeaderControl.xaml, MixItUp.WPF/Controls/Chat/ChatMessageHeaderControl.xaml.cs, MixItUp.WPF/Controls/Settings/ChatSettingsControl.xaml, MixItUp.WPF/Controls/Settings/ChatSettingsControl.xaml.cs
Add new setting to enable the feature
Add whisper control support and response
=> Add Whisperer Number feature

MixItUp.Base/Commands/PreMadeChatCommands.cs, MixItUp.Base/MixerAPI/ChatClientWrapper.cs, MixItUp.Base/ViewModel/Chat/ChatMessageViewModel.cs
This is a pretty simple fix to ensure the bot doesn't trigger the whisper logic.
=> Fix bot whispers to avoid self triggers

MixItUp.Base/Util/SpecialIdentifierStringBuilder.cs, MixItUp.Base/ViewModel/User/UserCurrencyViewModel.cs, MixItUp.WPF/Controls/MainControls/CurrencyAndRankControl.xaml
These two identifiers make it easy to make a chat command (!top10time) to send a message like:
Top 10 Viewers: $top10time
This will render:
Top 10 Viewers: 1) @Fred - 3 Hours & 15 Mins, 2) @David - 2 Hours & 5 Mins, ….
=> Add $top10time and $top10[CurrencySpecialIdentifier]

MixItUp.WPF/Controls/Chat/ChatMessageControl.xaml.cs, MixItUp.WPF/Controls/Users/UserProfileAvatarControl.xaml, MixItUp.WPF/Controls/Users/UserProfileAvatarControl.xaml.cs
=> Add tooltip to emote chat messages and make avatar pictures circular

MixItUp.WPF/Controls/Command/AdvancedCommandEditorControl.xaml.cs
OnLoaded may run more than once. This one control doesn't handle this case well. The quick solution is just to handle it politely.  If this causes problems later, maybe we need to clear the children and rebuild it.
=> Fix OnLoaded issue where it can get run more than once

MixItUp.Base/ViewModel/User/UserCurrencyViewModel.cs, MixItUp.Base/ViewModel/User/UserDataViewModel.cs, MixItUp.Base/ViewModel/User/UserViewModel.cs, MixItUp.WPF/Windows/Currency/CurrencyWindow.xaml, MixItUp.WPF/Windows/Currency/CurrencyWindow.xaml.cs
* Add offline version of all viewing minute related logic
* Add offline rate selection for currency/rank
=> Add ability to acquire offline curreny and rank

MixItUp.WPF/App.xaml, MixItUp.WPF/Controls/MainControls/ChatControl.xaml.cs, MixItUp.WPF/LoginWindow.xaml.cs, MixItUp.WPF/Windows/LoadingWindowBase.cs, MixItUp.WPF/Windows/Wizard/NewUserWizardWindow.xaml.cs
* Chat windows don't disconnect themselves
* Ensure MainWindow is set
* Use MainWindow to close the world
=> Clean up closing logic

MixItUp.Desktop/Services/DiscordService.cs, MixItUp.Desktop/Services/GameWispService.cs, MixItUp.Desktop/Services/SpotifyService.cs, MixItUp.Desktop/Services/StreamlabsOBSService.cs, MixItUp.Desktop/Services/StreamlabsService.cs, MixItUp.Desktop/Services/TiltifyService.cs, MixItUp.Desktop/Services/WindowsInputService.cs, MixItUp.WPF/Controls/MainControls/ChatControl.xaml.cs, MixItUp.WPF/Controls/MainControls/GiveawayControl.xaml.cs, MixItUp.WPF/Controls/MainControls/SongRequestControl.xaml.cs, obs-websocket-dotnet/Types.cs
When you hold an IDisposable thing you must implement IDisposable.
The P/Invoke for the mouse event requires IntPtr to ensure it is right on 32 and 64 bit.
Exceptions implement ISerializable and should have [Serializable] attribute.
=> Address various code analysis feedbacks

MixItUp.Base/MixerAPI/ChatClientWrapper.cs, MixItUp.Base/MixerAPI/ConstellationClientWrapper.cs, MixItUp.Base/MixerAPI/InteractiveClientWrapper.cs, MixItUp.Desktop/Services/GawkBoxService.cs
The basic idea here is to remove complexity, so I removed the ReconnectionHelper code. I then just did the basic thing here loop while Connect fails. I ran this for 19+ hours and had no problems. It disconnected  a couple of times and reconnected quickly.
=> Refactor retry logic

MixItUp.Base/Actions/ActionBase.cs, MixItUp.Base/Actions/StreamlabsAction.cs, MixItUp.Base/Services/IStreamlabsService.cs, MixItUp.Desktop/Services/StreamlabsService.cs, MixItUp.WPF/Changelog.html, MixItUp.WPF/Controls/Actions/ActionContainerControl.xaml.cs, MixItUp.WPF/Controls/Actions/StreamlabsActionControl.xaml, MixItUp.WPF/Controls/Actions/StreamlabsActionControl.xaml.cs, MixItUp.WPF/MixItUp.WPF.csproj
Implemented the basic features that required no special options
=> Add Streamlabs support for Roll Credits, Spin the Wheel, and Empty Jar

MixItUp.WPF/Controls/MainControls/ActionGroupControl.xaml, MixItUp.WPF/Controls/MainControls/ActionGroupControl.xaml.cs, MixItUp.WPF/Controls/MainControls/ChatCommandsControl.xaml, MixItUp.WPF/Controls/MainControls/ChatCommandsControl.xaml.cs
This should address #183 as it adds filtering and sorting.
=> Add filter and sort to custom commands

MixItUp.WPF/Controls/MainControls/ChatControl.xaml, MixItUp.WPF/Controls/MainControls/ChatControl.xaml.cs
This is a feature that has bugged me. I like to be able to press up arrow, enter to resend the last command.  This adds a complete command history. We could probably limit it to the last "N" commands, but I don't think that's really a necessary thing.
=> Make Up and Down arrow produce previous messages

MixItUp.WPF/Controls/MainControls/GameQueueControl.xaml.cs
We need to set the control to the correct value when the queue is updated
=> Fix game queue toggle

MixItUp.Base/Util/SpecialIdentifierStringBuilder.cs
=> Added $streamtitle special identifer

MixItUp.WPF/Controls/MainControls/ChannelControl.xaml.cs
First added a clear null check
Second put in a default value
Added a search fallback for suggestions
=> Fix game name glitch

MixItUp.Base/Commands/PermissionsCommandBase.cs, MixItUp.Base/ViewModel/Requirement/RequirementViewModel.cs, MixItUp.Base/ViewModel/Requirement/ThresholdRequirementViewModel.cs
Change whisper to chat and add command name
Track triggering users and charge currency and cooldown
Only send chat message once per user trigger
=> Fix Threshold Requirements

MixItUp.Base/Actions/OverlayAction.cs, MixItUp.Desktop/Services/OverlayWebServer.cs
Add a nonce
Fix URI parsing when query string is present
=> Fix local file caching

MixItUp.Base/MixerAPI/MixerConnectionWrapper.cs, MixItUp.Base/Util/SpecialIdentifierStringBuilder.cs
Used the GetChannelDetails to pull the value.
Also fixed typo in previous special identifier name.
=> Add $streamsubcount identifier

MixItUp.Base/Actions/ActionBase.cs, MixItUp.Base/Actions/CommandAction.cs, MixItUp.Base/Actions/ConditionalAction.cs, MixItUp.Base/Actions/TranslationAction.cs, MixItUp.Base/Actions/WebRequestAction.cs, MixItUp.Base/ChannelSession.cs, MixItUp.Base/Commands/PreMadeChatCommands.cs, MixItUp.Base/Commands/RemoteCommand.cs, MixItUp.Base/MixerAPI/ChatClientWrapper.cs, MixItUp.WPF/Controls/Actions/ActionContainerControl.xaml.cs, MixItUp.WPF/Controls/Actions/CommandActionControl.xaml, MixItUp.WPF/Controls/Actions/CommandActionControl.xaml.cs, MixItUp.WPF/Controls/Actions/TranslationActionControl.xaml.cs, MixItUp.WPF/Controls/Actions/WebRequestAction.xaml.cs, MixItUp.WPF/Controls/Command/BasicChatCommandEditorControl.xaml.cs, MixItUp.WPF/Controls/Command/ChatCommandDetailsControl.xaml.cs, MixItUp.WPF/Controls/Command/CommandReferenceControl.xaml.cs, MixItUp.WPF/Controls/Dialogs/RemoteReferenceCommandDialogControl.xaml.cs, MixItUp.WPF/Controls/Requirement/CooldownRequirementControl.xaml.cs, MixItUp.WPF/MixItUp.WPF.csproj, MixItUp.WPF/Windows/Command/GameCommandWindow.xaml.cs
Add the command action and controls.
=> Add command action

MixItUp.Base/Actions/WebRequestAction.cs, MixItUp.Base/Commands/ChatCommand.cs, MixItUp.Base/Commands/CommandBase.cs, MixItUp.Base/Commands/GameCommand.cs, MixItUp.Base/Commands/PreMadeChatCommands.cs, MixItUp.WPF/Controls/Command/BasicChatCommandEditorControl.xaml.cs, MixItUp.WPF/Controls/Command/ChatCommandDetailsControl.xaml.cs, MixItUp.WPF/Windows/Command/GameCommandWindow.xaml.cs
* Add User-Agent string
* Make all command triggers case insensitive
=> Various fixes

MixItUp.Base/Services/IStreamingSoftwareService.cs, MixItUp.Desktop/Services/OBSService.cs, MixItUp.Desktop/Services/StreamlabsOBSService.cs, MixItUp.Desktop/Services/XSplitWebServer.cs, MixItUp.WPF/Controls/Actions/StreamingSoftwareActionControl.xaml, MixItUp.WPF/Controls/Actions/StreamingSoftwareActionControl.xaml.cs
Add starting the buffer, and better error messages
=> Finish Replay Buffer Work

MixItUp.Base/ChannelSession.cs, MixItUp.Base/Services/ITelemetryService.cs, MixItUp.Base/Services/ServicesHandlerBase.cs, MixItUp.Base/Util/Logger.cs, MixItUp.Desktop/MixItUp.Desktop.csproj, MixItUp.Desktop/Services/DesktopServicesHandler.cs, MixItUp.Desktop/Services/DesktopTelemetryService.cs, MixItUp.Desktop/packages.config, MixItUp.WPF/App.xaml.cs, MixItUp.WPF/Controls/MainControls/MainControlBase.cs
Add telemetry data and ensure it obeys the opt-out setting.
=> Add application insights

MixItUp.Base/IChannelSettings.cs, MixItUp.Base/Services/IOverlayService.cs, MixItUp.Base/Services/ISongRequestService.cs, MixItUp.Base/Services/ISpotifyService.cs, MixItUp.Desktop/DesktopChannelSettings.cs, MixItUp.Desktop/Overlay/OverlayPage.html, MixItUp.Desktop/Services/DesktopSongRequestService.cs, MixItUp.Desktop/Services/SpotifyService.cs, MixItUp.WPF/Controls/MainControls/MainControlBase.cs, MixItUp.WPF/Controls/MainControls/SongRequestControl.xaml, MixItUp.WPF/Controls/MainControls/SongRequestControl.xaml.cs
Add default playlist and allow curated lists
Add song request volume control
=> Add song request volume control

MixItUp.Base/Actions/SongRequestAction.cs, MixItUp.Base/Services/ISongRequestService.cs, MixItUp.Base/Util/SpecialIdentifierStringBuilder.cs, MixItUp.Desktop/Services/DesktopSongRequestService.cs, MixItUp.WPF/Controls/MainControls/SongRequestControl.xaml
Add user names to song request list
Add cancel last requested song by user
Add $currentsongtitle, $currentsongusername, $nextsongtitle, $nextsongusername identifiers
=> Add user features to song request

MixItUp.Base/Services/MixItUpService.cs, MixItUp.Base/Util/Logger.cs
Remove the sending of exceptions to the MIU service.
=> Remove error reports

MixItUp.WPF/Controls/Chat/ChatMessageHeaderControl.xaml.cs, MixItUp.WPF/Controls/Chat/ChatUserControl.xaml.cs, MixItUp.WPF/Controls/Dialogs/UserDialogControl.xaml.cs, MixItUp.WPF/Controls/MainControls/AboutControl.xaml, MixItUp.WPF/Controls/MainControls/ChatControl.xaml.cs, MixItUp.WPF/Controls/MainControls/InteractiveControl.xaml.cs, MixItUp.WPF/Controls/Services/MixerBotAccountServiceControl.xaml.cs, MixItUp.WPF/Controls/Store/ListingUserReviewControl.xaml.cs, MixItUp.WPF/Controls/Store/MainStoreControl.xaml.cs, MixItUp.WPF/Controls/Users/UserProfileAvatarControl.xaml.cs, MixItUp.WPF/Windows/Wizard/NewUserWizardWindow.xaml.cs
Disable bad website link (No issue)
Fix image downloading to be more reliable (#220)
Fix crash when using Process.Start (#222)
=> Fix image downloading to be more reliable

MixItUp.Desktop/MixItUp.Desktop.csproj, MixItUp.Desktop/Services/WindowsDeveloperAPIService.cs, MixItUp.Desktop/packages.config, MixItUp.WPF/MixItUp.WPF.csproj, MixItUp.WPF/packages.config
Removed HttpListener
Add Routes and Controllers
=> Rewrite api code

MixItUp.Base/Model/DeveloperAPIs/UserCurrencyDeveloperAPIModel.cs, MixItUp.Base/Model/DeveloperAPIs/UserDeveloperAPIModel.cs, MixItUp.Desktop/Services/DeveloperAPI/UserController.cs, docs/swagger.yaml
ViewingMinutes should be optional (no change if not provided)
The currencies returned should be ALL currencies, not just ones the user has.
=> Update dev APIs based on usability feedback

MixItUp.WPF/Controls/Chat/ChatUserControl.xaml.cs, MixItUp.WPF/Controls/MainControls/ChatControl.xaml, MixItUp.WPF/Controls/MainControls/ChatControl.xaml.cs, MixItUp.WPF/Themes/MixItUpTheme.Common.xaml
Ignore the typo in the branch name. :)  But, this was surprisingly easy.  It seems to work good, but I'd love to test with more users.
=> Detect @ tag and show top 5 choices

MixItUp.WPF/Controls/Chat/ChatMessageControl.xaml, MixItUp.WPF/Controls/Chat/ChatMessageControl.xaml.cs, MixItUp.WPF/Controls/MainControls/ChatControl.xaml
This was pretty easy. I had to change around the padding/spacing a little. Then I just load/set the foreground/background from the respective theme. All my testing (colors and such) looked pretty good.
=> Highlight the streamer in tags and whispers.

MixItUp.WPF/Controls/MainControls/ChannelControl.xaml, MixItUp.WPF/Controls/MainControls/ChannelControl.xaml.cs
This fixes the issue (#192) we were seeing before where typing in stuff would change unexpectedly.
=> Refactor game name box to use intellisense like code.

MixItUp.Base/MixerAPI/InteractiveClientWrapper.cs, MixItUp.Base/ViewModel/User/UserContainerViewModel.cs, MixItUp.Base/ViewModel/User/UserViewModel.cs
- Adding logic to deal with unauthenticated users that can connect to interactive
- Removing background refresh of interactive participants
=> Adding logic to deal with unauthenticated users that can connect to interactive

MixItUp.Base/Actions/SpecialIdentifierAction.cs, MixItUp.Base/MixItUp.Base.csproj, MixItUp.WPF/Controls/Actions/SpecialIdentifierActionControl.xaml, MixItUp.WPF/Controls/Actions/SpecialIdentifierActionControl.xaml.cs, MixItUp.WPF/MixItUp.WPF.csproj, MixItUp.WPF/packages.config
This adds the ability to do math calculations in special identifier actions.
If anything goes wrong (parsing, formula issues, etc), the error is logged and we treat it as "0".
=> Add math library to special identifier action

MixItUp.Base/Services/ISongRequestService.cs, MixItUp.Base/Util/SpecialIdentifierStringBuilder.cs, MixItUp.Desktop/Services/SongRequestService.cs
If it can't find the image it'll be an empty string.  I know we have a feature gap here however.  We need either an overlay widget for song requests OR we need an event that triggers when the song changes.
=> Add album images

MixItUp.Base/Actions/TwitterAction.cs, MixItUp.Base/Services/ITwitterService.cs, MixItUp.Desktop/MixItUp.Desktop.csproj, MixItUp.Desktop/Services/TwitterService.cs, MixItUp.WPF/Controls/Actions/TwitterActionControl.xaml, MixItUp.WPF/Controls/Actions/TwitterActionControl.xaml.cs
Just a new feature that came to mind, figured it might be nice. Review and decide if we want this or not.
=> Add image attachments to tweets

MixItUp.Desktop/Services/SongRequestService.cs
Fixed by ensuring only one init/disable can happen per cycle.
=> Fix song request loop

MixItUp.Base/Actions/WebRequestAction.cs
Adding support for arrays in web request JSON to Special Identifier processing
=> Adding support for arrays in web request JSON to Special Identifier processing

MixItUp.Base/ViewModel/User/UserDataViewModel.cs
I'm not quite sure what happened here, but, I BELIEVE this is needed to save a user's custom titles?
=> Make them save to the user's options

MixItUp.WPF/Controls/Services/MixerBotAccountServiceControl.xaml
Fixed a typo in the services UI under the Mixer Bot Account service.
=> Fixed Typo On Services UI

MixItUp.Base/Actions/StreamingSoftwareAction.cs, MixItUp.Base/Services/IStreamingSoftwareService.cs, MixItUp.Desktop/Services/OBSService.cs, MixItUp.Desktop/Services/StreamlabsOBSService.cs, MixItUp.Desktop/Services/XSplitWebSocketServer.cs, MixItUp.WPF/Controls/Actions/StreamingSoftwareActionControl.xaml, MixItUp.WPF/Controls/Actions/StreamingSoftwareActionControl.xaml.cs
I figured I'd send a PR here to make sure this jives with your expectations.
=> Add set scene collection for OBS Studio

MixItUp.Base/Actions/ActionBase.cs, MixItUp.Base/Actions/OvrStreamAction.cs, MixItUp.Base/ChannelSession.cs, MixItUp.Base/IChannelSettings.cs, MixItUp.Base/Services/IOvrStreamService.cs, MixItUp.Base/Services/ServicesHandlerBase.cs, MixItUp.Desktop/DesktopChannelSettings.cs, MixItUp.Desktop/MixItUp.Desktop.csproj, MixItUp.Desktop/Services/DesktopServicesHandler.cs, MixItUp.Desktop/Services/OvrStreamService.cs, MixItUp.WPF/Controls/Actions/ActionContainerControl.xaml.cs, MixItUp.WPF/Controls/Actions/OvrStreamActionControl.xaml, MixItUp.WPF/Controls/Actions/OvrStreamActionControl.xaml.cs, MixItUp.WPF/Controls/MainControls/ServicesControl.xaml.cs, MixItUp.WPF/Controls/Services/OvrStreamServiceControl.xaml, MixItUp.WPF/Controls/Services/OvrStreamServiceControl.xaml.cs, MixItUp.WPF/MixItUp.WPF.csproj
Add the service and it's related actions.
=> Add OvrStream support for the next preview release

MixItUp.Desktop/Overlay/OverlayPage.html, MixItUp.Desktop/Overlay/webSocketWrapper.js, MixItUp.Desktop/Services/OverlayService.cs
Remove need for specifying the websocket port as it can detect it.  Also, detect if HTTPS and use WSS in that case.
=> Clean up overlay code

MixItUp.Base/Commands/StoreCommandUpgrader.cs, MixItUp.Base/Model/Overlay/OverlayLeaderboardListItemModel.cs, MixItUp.Base/ViewModel/Controls/Overlay/OverlayLeaderboardListItemViewModel.cs, MixItUp.WPF/Controls/Overlay/OverlayLeaderboardListItemControl.xaml, MixItUp.WPF/Controls/Overlay/OverlayLeaderboardListItemControl.xaml.cs
Can you give this a review. Want to make sure I didn't mess it up. :)
=> Add new leader command to leaderboard overlay widget

MixItUp.Base/Services/External/OAuthExternalServiceBase.cs
oauth webpage design refresh.
Update to OAuthExternalServiceBase.cs
=> OAuth webpage refresh
